package mgh.morteza.core.designsystem

const val ALPHA_ON_SURFACE_VARIANT_MEDIUM_EMPHASIS = 0.4F
const val ALPHA_ON_SURFACE_MEDIUM_EMPHASIS = 0.4F
const val ALPHA_ON_SURFACE_CONTAINER_LOWEST_MEDIUM_EMPHASIS = 0.4F